# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-06 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myalbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=40)),
                ('album_logo', models.CharField(max_length=1000)),
                ('photosnumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='myinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('friends', models.CharField(max_length=4)),
                ('profilepic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=1000)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.myalbum')),
            ],
        ),
        migrations.AddField(
            model_name='myalbum',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.myinfo'),
        ),
    ]
